# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_NO_KERNEL := false
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

BOARD_EGL_CFG := device/Alcatel/U5A_PLUS_3G/egl.cfg

TARGET_PREBUILT_KERNEL := kernel/Alcatel/U5A_PLUS_3G/kernel
TARGET_PREBUILT_DTB := kernel/Alcatel/U5A_PLUS_3G/kernel_dtb

BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_TAGS_OFFSET := 0x0e000000

# MediaTek specific
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true

# Recovery
TARGET_RECOVERY_FSTAB := device/Alcatel/U5A_PLUS_3G/recovery.fstab
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_SDCARD_ON_DATA := true
