$(call inherit-product, $(SRC_TARGET_DIR)/product/generic.mk)
PRODUCT_BRAND :=Alcatel
PRODUCT_DEVICE :=U5A_PLUS_3G
PRODUCT_NAME :=U5A_PLUS_3G

PRODUCT_AAPT_CONFIG :=hdpi
PRODUCT_AAPT_PREF_CONFIG :=hdpi
PRODUCT_CHARACTERISTICS :=phone
